apiVersion: v1
kind: Service
metadata:
  name: moviedatastore-restapp-clb-service
  labels: 
    app: moviedatastore-restapp
spec:
  type: LoadBalancer
  selector:
    app: moviedatastore-restapp
  ports: 
    - port: 80
      targetPort: 8080
